### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Mennaruuk** [jslee02/awesome-collision-detection#7]
## For: https://jslee02.github.io/awesome-collision-detection/
> 3D collision detection: a survey (2001), P. Jiménez et al. [**pdf**]

I saw the link is FTP. I think it'd be much better to replace it with a direct HTTPS PDF link. https://users.soe.ucsc.edu/~pang/161/w06/notes/jtt01.pdf. [Archive](https://web.archive.org/web/20210222085803/https://users.soe.ucsc.edu/~pang/161/w06/notes/jtt01.pdf).
&nbsp;

> Fast Approximate Nearest Neighbors with Automatic Algorithm Configuration (2009), M. Muja and D. Lowe. [**pdf**, code]

The old PDF link is down. I found a working link at PSU [here](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.160.1721&rep=rep1&type=pdf). Also an [archive ](https://web.archive.org/web/20180304182151/https://www.cs.ubc.ca/~mariusm/uploads/FLANN/flann_visapp09.pdf)of the old link. 
&nbsp;
> Contributions are very welcome! Please read the **contribution guidelines** first. Also, please feel free to report any error.

Unfortunately, [CONTRIBUTING.md](https://github.com/jslee02/awesome-collision-detection/blob/master/CONTRIBUTING.md) is down.

&nbsp;
&nbsp;

## For: https://github.com/jslee02/awesome-collision-detection
> Robust contact generation for robot simulation with unstructured meshes (2013), K. Hauser. [pdf, web]

PDF and site are down. [Here's a better PDF link](https://motion.cs.illinois.edu/papers/ISRR2013-RobustContact.pdf). [Archive of the website](https://web.archive.org/web/20190916070729/http://motion.pratt.duke.edu/simulation/index.html).
&nbsp;
> Collision Detection (**code**) by Jeff Thompson - This book explains the algorithms behind those collisions using basic shapes like circles, rectangles, and lines so you can implement them into your own projects.

The code link (https://github.com/jslee02/awesome-collision-detection/blob/master) is down.
&nbsp;
> Contributions are very welcome! Please read the contribution guidelines first. Also, please feel free to report any error.

As aforementioned, [CONTRIBUTING.md](https://github.com/jslee02/awesome-collision-detection/blob/master/CONTRIBUTING.md) is down.

I don't get physics, but whatever you're doing is cool, and I hope lots of good comes out of it!

**Comment by Mennaruuk** [comment]
Forgot to include the first PDF's archive, it's here: https://web.archive.org/web/20210222085803/https://users.soe.ucsc.edu/~pang/161/w06/notes/jtt01.pdf

**Comment by jslee02** [comment]
Thank you for pinpointing the broken links! They should be fixed by https://github.com/jslee02/awesome-collision-detection/commit/fbb12e312416187e8d6bf612435d6162da4f7f2d
